(function(root){
'use strict';
const names={price:'价格判断',event:'一件事',goal:'一个目标',letter:'写给未来'};
const labels={submitted:'待收录',sealed:'封存中',due:'到期待揭示',revealed:'已揭示',provisional:'异议期',disputed:'有异议',review:'评审中',judged:'已裁决',unrevealed:'未揭示'};
const day=(n=0)=>{const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const clone=x=>JSON.parse(JSON.stringify(x));
function draft(){return {kind:'price',text:'',date:day(30),time:'09:00',asset:'BTC',operator:'高于',target:'',condition:'',visibility:'sealed',stake:false};}
function normalise(d){const n={...draft(),...d};if(!names[n.kind])n.kind='price';if(!['price','event'].includes(n.kind))n.stake=false;if(n.kind==='letter')n.visibility='sealed';return n;}
function validate(d){if(!names[d.kind])return '请选择内容类型。';if(typeof d.text!=='string'||d.text.trim().length<4||d.text.length>1000)return '请写下 4～1000 个字的内容。';if(!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(d.time||''))return '请选择有效的日期和时间。';const parsed=new Date(`${d.date}T${d.time}:00+08:00`);if(!Number.isFinite(parsed.getTime())||new Date(d.date+'T00:00:00Z').toISOString().slice(0,10)!==d.date||parsed.getTime()<=Date.now())return '请选择未来的开舱时间。';if(d.kind==='price'&&(!Number.isFinite(Number(d.target))||Number(d.target)<=0))return '请填写大于零的目标价格。';if(['event','goal'].includes(d.kind)&&(!d.condition||d.condition.trim().length<4))return '请写明判断条件和证据来源。';return '';}
function condition(d){return d.kind==='price'?`${d.date} 北京时间 ${d.time}，${d.asset} 价格${d.operator} ${d.target} 美元；等于阈值记为未中（体验规则）`:d.kind==='letter'?'到期公开读信（本原型演示方式），不裁决、不计分。':d.condition;}
function fee(d,resident){return {identity:!resident||resident.pending?0.14196:0,backing:['price','event'].includes(d.kind)&&d.stake?0.06196:0};}
function result(r){if(r.status==='unrevealed')return 'u';if(r.status!=='judged')return 'w';return r.hit?'h':'m';}
function stats(records){const forecasts=records.filter(r=>['price','event'].includes(r.kind)&&r.stake),judged=forecasts.filter(r=>r.status==='judged'),hits=judged.filter(r=>r.hit).length,score=judged.reduce((s,r)=>s+(r.hit?1-r.p:-r.p),0),goals=records.filter(r=>r.kind==='goal'&&r.status==='judged');return {count:judged.length,hits,score,average:judged.length?score/judged.length:null,rate:judged.length?hits/judged.length:null,unrevealed:forecasts.filter(r=>r.status==='unrevealed').length,pending:forecasts.filter(r=>!['judged','unrevealed'].includes(r.status)).length,promise:goals.reduce((s,r)=>s+r.goalScore,0),goalCount:goals.length,total:records.length};}
function fixtures(){const people=[['spongemochi','SpongeMochi','26.2.168','human','hhmhhhm', [.3,.45,.6,.25,.4,.55,.5]],['nova','nova.agent','72.2.168','agent','hmhhhhh',[.6,.5,.4,.7,.55,.65,.4]],['hong','洪七公','47.2.168','human','hmhmhhm',[.35,.6,.4,.65,.5,.25,.7]],['north','北辰','18.2.168','human','hhmmhh',[.2,.6,.7,.3,.45,.5]],['echo','echo.agent','86.2.168','agent','mhmmhh',[.5,.35,.65,.7,.6,.55]],['mumu','木木','36.2.168','human','h',[.25]]];const residents=people.map(p=>({id:p[0],name:p[1],address:p[2],type:p[3],pending:false}));residents.push({id:'judge',name:'判官',address:'1.2.168',type:'judge',pending:false});let records=[];people.forEach((p,pi)=>p[4].split('').forEach((mark,i)=>{const at=day(-28+i*3);records.push({id:`seed-${pi}-${i}`,owner:p[0],kind:'price',text:`我判断 ${i%2?'ETH':'BTC'} 会在约定日高于目标价格。`,date:at,created:day(-35),createdAt:day(-35)+'T09:00:00+08:00',condition:`${at} 北京时间 09:00，${i%2?'ETH > 3000':'BTC > 95000'} 美元（示例条件）`,stake:true,visibility:'public',status:'judged',due:true,p:p[5][i],hit:mark==='h',evidence:'虚构演示结果。没有实际调用价格源，也没有真实交易凭证。',sample:true,history:[{label:'发送承诺',at:day(-35)},{label:'判官收录，固定评分参数',at:day(-35)},{label:'到期揭示',at},{label:'示例裁决',at}]});}));
 [['spongemochi','unrevealed'],['mumu','unrevealed'],['hong','unrevealed'],['echo','unrevealed'],['nova','sealed']].forEach(([owner,status],i)=>records.push({id:'seed-wait-'+i,owner,kind:'event',text:'社区会在约定日前举行一次公开活动。',condition:'以活动公告与现场公开记录为证据。',date:status==='sealed'?day(7):day(-8),created:day(-30),createdAt:day(-30)+'T09:00:00+08:00',stake:true,visibility:'sealed',status,due:status!=='sealed',p:.4,sample:true,history:[{label:'发送承诺与判官收录',at:day(-30)},{label:status==='sealed'?'等待约定日期':'七天宽限期后仍未揭示',at:day(-1)}]}));
 records.push({id:'seed-goal',owner:'spongemochi',kind:'goal',text:'我会发布自己的第一个开源作品。',condition:'公开仓库与可访问的演示链接。',date:day(-10),created:day(-25),createdAt:day(-25)+'T09:00:00+08:00',stake:false,visibility:'public',status:'judged',due:true,hit:true,goalScore:1,evidence:'示例：已提交公开仓库与演示，经模拟评审确认。',sample:true,history:[{label:'封存目标',at:day(-25)},{label:'提交证据，进入评审',at:day(-10)},{label:'模拟七天评审结束，确认兑现',at:day(-3)}]});
 return {version:3,residents,records,active:null,draft:draft()};}
class Store{
 constructor(data){this.data=data&&data.version===3&&Array.isArray(data.residents)&&Array.isArray(data.records)?clone(data):fixtures();}
 get residents(){return this.data.residents;}get records(){return this.data.records;}get active(){return this.residents.find(p=>p.id===this.data.active)||null;}
 get(id){return this.records.find(r=>r.id===id);}by(owner){return this.records.filter(r=>r.owner===owner);}
 select(id){const p=this.residents.find(p=>p.id===id&&p.type!=='judge');if(!p)throw Error('请选择居民身份。');this.data.active=p.id;return p;}
 createResident(name,type){if(!name.trim())throw Error('请填写居民名称。');const id='resident-'+Date.now()+'-'+Math.random().toString(36).slice(2,6);const p={id,name:name.trim().slice(0,24),address:`${169+this.residents.filter(p=>p.local).length}.2.168`,type:type==='agent'?'agent':'human',pending:true,local:true};this.residents.push(p);this.data.active=id;return p;}
 completeResidence(){const resident=this.active;if(!resident||!resident.local)throw Error('没有待落户的本地居民。');if(!resident.pending)return resident;resident.pending=false;resident.residenceReceipt={simulated:true,at:new Date().toISOString(),estimatedCost:0.14196};return resident;}
 cancelResidence(){const resident=this.active;if(!resident||!resident.local||!resident.pending)throw Error('没有可取消的待落户身份。');this.data.residents=this.residents.filter(p=>p.id!==resident.id);this.data.active=null;return resident;}
 submit(input){const d=normalise(input),err=validate(d);if(err)throw Error(err);if(!this.active)throw Error('请先选择居民身份。');if(this.active.pending)throw Error('请先完成居民落户，再发送承诺。');const id='local-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),now=new Date().toISOString();const costs=fee(d,this.active);const r={...d,id,owner:this.active.id,created:day(),createdAt:now,condition:condition(d),status:'submitted',due:false,sample:true,local:true,costs,history:[{label:'模拟发送承诺给判官 1.2.168',at:now}]};this.records.push(r);this.data.draft=draft();return r;}
 transition(id,action,payload={}){const r=this.get(id);if(!r)throw Error('没有找到这条记录。');const add=label=>r.history.push({label,at:new Date().toISOString(),simulated:true});
 if(action==='receive'){if(r.status!=='submitted')throw Error('该承诺已经收录。');r.status=r.visibility==='public'?'revealed':'sealed';if(r.stake)r.p=.35;r.receipt=true;add(r.stake?'模拟判官收录，固定示例概率参数（裁决时揭示）':'模拟判官收录，不计判断分');}
 else if(action==='due'){if(!['sealed','revealed'].includes(r.status)||r.due)throw Error('当前不能推进到期。');r.due=true;if(r.status==='sealed')r.status='due';add('模拟时间到达约定时刻');}
 else if(action==='reveal'){if(r.status!=='due')throw Error('需先到期才能揭示。');r.status='revealed';add(r.kind==='letter'?'模拟开信，本记录不裁决、不计分':'模拟揭示原文，等待核对证据');}
 else if(action==='timeout'){if(r.status!=='due')throw Error('只有到期且未揭示的记录可演示超时。');r.status='unrevealed';add('模拟超过七天揭示宽限期，标记未揭示');}
 else if(action==='judge'){if(r.status!=='revealed'||!r.due||!['price','event'].includes(r.kind))throw Error('当前不能裁决。');if(!payload.evidence||payload.evidence.trim().length<4)throw Error('请提供证据说明。');if(r.stake&&!Number.isFinite(r.p))throw Error('缺少事前固定的评分参数。');r.hit=payload.hit===true;r.evidence=payload.evidence.trim();r.status=r.kind==='event'?'provisional':'judged';add(r.kind==='event'?'模拟事件初判，进入七天异议期（暂不计分）':'模拟价格裁决，公开参数与结果');}
 else if(action==='finalize'){if(r.status!=='provisional')throw Error('仅无异议的事件初判可结算。');r.status='judged';add('模拟七天异议期结束，无异议，结果正式计入履历');}
 else if(action==='challenge'){if(r.status!=='provisional')throw Error('当前不在事件异议期。');if(!payload.evidence||payload.evidence.trim().length<4)throw Error('请说明异议依据。');r.challenge=payload.evidence.trim();r.status='disputed';add('提交模拟异议，保留初判与证据，暂停结算');}
 else if(action==='evidence'){if(r.status!=='revealed'||r.kind!=='goal'||!r.due)throw Error('目标到期揭示后才能提交证据。');if(!payload.evidence||payload.evidence.trim().length<4)throw Error('请填写完成证据。');r.evidence=payload.evidence.trim();r.status='review';add('模拟提交证据与初审，进入七天居民评审期');}
 else if(action==='review'){if(r.status!=='review')throw Error('当前不在目标评审期。');if(![1,.5,-1].includes(payload.score))throw Error('请选择有效的守约结果。');r.status='judged';r.goalScore=payload.score;r.hit=payload.score>0;add('模拟七天评审结束：'+(payload.score===1?'经评审兑现 +1':payload.score===.5?'仅自证 +0.5':'未兑现 −1'));}
 else throw Error('未知操作。');return r;}
}
const api={Store,fixtures,stats,result,day,names,labels,draft,normalise,validate,condition,fee};root.FlowModel=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
