const assert=require('node:assert/strict'),M=require('./flow-model');let tests=0;
function test(name,fn){fn();tests++;console.log('通过：'+name);}
function setup(kind='price',stake=true){const s=new M.Store();s.select('spongemochi');const r=s.submit({...M.draft(),kind,stake,text:'这是一条用于验证流程的承诺',target:'95000',condition:'以公开公告与证据为判断依据'});return {s,r};}
function ready(s,r){s.transition(r.id,'receive');s.transition(r.id,'due');s.transition(r.id,'reveal');}
test('未到期不可裁决，重复裁决不能重复计分',()=>{const {s,r}=setup();assert.throws(()=>s.transition(r.id,'judge',{hit:true,evidence:'示例证据'}));ready(s,r);s.transition(r.id,'judge',{hit:true,evidence:'示例证据'});assert.equal(M.stats([r]).score,.65);assert.throws(()=>s.transition(r.id,'judge',{hit:true,evidence:'示例证据'}));});
test('公开原文仍须等到约定时刻',()=>{const {s}=setup();const r=s.submit({...M.draft(),visibility:'public',text:'立即公开的一次价格判断',target:1,stake:true});s.transition(r.id,'receive');assert.equal(r.status,'revealed');assert.throws(()=>s.transition(r.id,'judge',{hit:true,evidence:'示例证据'}));s.transition(r.id,'due');s.transition(r.id,'judge',{hit:false,evidence:'示例证据'});assert.equal(M.stats([r]).score,-.35);});
test('事件初判不计分，异议冻结结果',()=>{const {s,r}=setup('event');ready(s,r);s.transition(r.id,'judge',{hit:true,evidence:'示例事件证据'});assert.equal(M.stats([r]).count,0);s.transition(r.id,'challenge',{evidence:'存在相反公开证据'});assert.throws(()=>s.transition(r.id,'finalize'));assert.equal(M.stats([r]).score,0);});
test('事件无异议期结束后进入判断分',()=>{const {s,r}=setup('event');ready(s,r);s.transition(r.id,'judge',{hit:true,evidence:'示例事件证据'});s.transition(r.id,'finalize');assert.equal(M.stats([r]).score,.65);assert.throws(()=>s.transition(r.id,'finalize'));});
test('目标三种守约结果与判断分分开',()=>{for(const score of [1,.5,-1]){const {s,r}=setup('goal');ready(s,r);s.transition(r.id,'evidence',{evidence:'示例目标完成证据'});assert.equal(M.stats([r]).promise,0);s.transition(r.id,'review',{score});assert.equal(M.stats([r]).promise,score);assert.equal(M.stats([r]).count,0);assert.equal(r.stake,false);}});
test('未来信只揭示，不裁决、不计分',()=>{const {s,r}=setup('letter');ready(s,r);assert.equal(r.status,'revealed');assert.throws(()=>s.transition(r.id,'judge',{hit:true,evidence:'示例证据'}));assert.equal(M.stats([r]).score,0);assert.equal(r.stake,false);});
test('未揭示保留履历但不作为命中',()=>{const {s,r}=setup();s.transition(r.id,'receive');s.transition(r.id,'due');s.transition(r.id,'timeout');assert.equal(M.stats([r]).unrevealed,1);assert.equal(M.stats([r]).count,0);assert.throws(()=>s.transition(r.id,'reveal'));});
test('普通价格封存不计入判断榜',()=>{const {s,r}=setup('price',false);ready(s,r);s.transition(r.id,'judge',{hit:true,evidence:'示例证据'});assert.equal(M.stats([r]).count,0);assert.equal(r.costs.backing,0);});
test('身份必须先独立落户，判官不能发预测',()=>{const s=new M.Store();assert.throws(()=>s.select('judge'));s.createResident('测试居民','agent');const input={...M.draft(),text:'测试新身份首次封存',target:1,stake:true};assert.throws(()=>s.submit(input),/先完成居民落户/);const p=s.completeResidence();assert.equal(p.residenceReceipt.estimatedCost,.14196);const a=s.submit(input),b=s.submit(input);assert.equal(a.costs.identity,0);assert.equal(b.costs.identity,0);assert.equal(b.costs.backing,.06196);assert.equal(s.completeResidence(),p);});
test('取消待落户身份不会留下虚构居民或丢失草稿',()=>{const s=new M.Store();const draft={...M.draft(),text:'稍后再提交的草稿内容'};s.data.draft=draft;const p=s.createResident('取消的居民','human');s.cancelResidence();assert.equal(s.active,null);assert(!s.residents.some(r=>r.id===p.id));assert.deepEqual(s.data.draft,draft);});
test('序列化后身份与完整履历能恢复',()=>{const {s,r}=setup();ready(s,r);s.transition(r.id,'judge',{hit:true,evidence:'示例证据'});const copy=new M.Store(JSON.parse(JSON.stringify(s.data)));assert.equal(copy.active.id,'spongemochi');assert.deepEqual(copy.get(r.id),r);assert.deepEqual(M.stats(copy.records),M.stats(s.records));});
test('提交前校验内容、日期和明确条件',()=>{assert(M.validate({...M.draft(),text:'完整的价格判断内容',target:0}));assert(M.validate({...M.draft(),text:'完整的价格判断内容',target:1,date:M.day(-1)}));assert(M.validate({...M.draft(),kind:'event',text:'完整的事件判断内容',condition:''}));});
test('用户自定开舱时间会进入判定条件',()=>{const d={...M.draft(),text:'未来某个时刻的价格判断',target:100000,time:'18:45'};assert.equal(M.validate(d),'');assert.match(M.condition(d),/北京时间 18:45/);assert(M.validate({...d,time:'24:00'}));});
console.log(`${tests} 组流程测试全部通过`);
