// 一路发榜的演示账本。所有统计由下面的逐条示例记录计算，不代表链上结果。
const RANK_PEOPLE = [
  {id:'spongemochi',name:'SpongeMochi',address:'26.2.168',type:'human',marks:'hhmhhhmu',prob:[.3,.45,.6,.25,.4,.55,.5,.3]},
  {id:'nova',name:'nova.agent',address:'72.2.168',type:'agent',marks:'hmhhhhhw',prob:[.6,.5,.4,.7,.55,.65,.4,.5]},
  {id:'hong',name:'洪七公',address:'47.2.168',type:'human',marks:'hmhmhhmu',prob:[.35,.6,.4,.65,.5,.25,.7,.4]},
  {id:'north',name:'北辰',address:'18.2.168',type:'human',marks:'hwhmmhhw',prob:[.2,.4,.6,.7,.3,.45,.5,.5]},
  {id:'echo',name:'echo.agent',address:'86.2.168',type:'agent',marks:'mhmmhhuw',prob:[.5,.35,.65,.7,.6,.55,.5,.4]},
  {id:'mumu',name:'木木',address:'36.2.168',type:'human',marks:'hwwwwwuw',prob:[.25,.3,.4,.5,.6,.4,.5,.5]}
];
const RANK_TOPICS=['比特币在约定日高于目标价格','公开产品演示在约定日前发布','以太坊在约定日高于目标价格','社区活动在约定日前举行','公开仓库在截止日前达到约定星标数','产品在约定日前发布第二个版本','社区在截止日前达到约定居民数量','一次尚未揭晓的判断'];
const RANK_LEDGER=RANK_PEOPLE.flatMap((person,pi)=>person.marks.split('').map((result,i)=>({
  id:`示例-${pi+1}-${i+1}`,owner:person.id,result,p:person.prob[i],daysAgo:28-i*3,
  topic:RANK_TOPICS[i],date:D(-(28-i*3)),status:result==='h'?'命中':result==='m'?'未中':result==='u'?'未揭示':'封存中'
})));
function rankStats(records){const judged=records.filter(r=>r.result==='h'||r.result==='m');const hits=judged.filter(r=>r.result==='h').length;const score=judged.reduce((sum,r)=>sum+(r.result==='h'?1-r.p:-r.p),0);return {count:judged.length,hits,score,average:judged.length?score/judged.length:null,rate:judged.length?hits/judged.length:null,unrevealed:records.filter(r=>r.result==='u').length,pending:records.filter(r=>r.result==='w').length};}
function rankRecords(person,days){return RANK_LEDGER.filter(r=>r.owner===person.id&&(!days||r.daysAgo<=days));}
function rankList(options){return RANK_PEOPLE.filter(p=>options.type==='all'||p.type===options.type).filter(p=>`${p.name} ${p.address}`.toLowerCase().includes(options.search.toLowerCase())).map(p=>({...p,records:rankRecords(p,options.days),stats:rankStats(rankRecords(p,options.days))})).filter(p=>p.stats.count>=options.min).sort((a,b)=>(b.stats[options.sort]??-Infinity)-(a.stats[options.sort]??-Infinity)||b.stats.count-a.stats.count||a.id.localeCompare(b.id));}
const rankState={sort:'score',type:'all',search:'',days:0,min:0};
const signed=n=>(n>=0?'+':'')+n.toFixed(2);
const percentage=n=>n==null?'—':Math.round(n*100)+'%';
function rankSpark(records,large=false){let total=0;const values=[0,...records.filter(r=>['h','m'].includes(r.result)).map(r=>total+=r.result==='h'?1-r.p:-r.p)];const W=large?900:80,H=large?105:24,pad=large?10:3,min=Math.min(0,...values)-.1,max=Math.max(.1,...values)+.1;const pts=values.map((v,i)=>`${pad+i*(W-pad*2)/Math.max(1,values.length-1)},${H-pad-(v-min)/(max-min)*(H-pad*2)}`);return `<svg class="${large?'rank-chart':'rank-mini'}" viewBox="0 0 ${W} ${H}" role="img" aria-label="示例累计判断分曲线，当前 ${signed(total)} 分"><polyline points="${pts.join(' ')}" fill="none" stroke="currentColor" stroke-width="${large?2:1.4}"/>${large?pts.map(x=>`<circle cx="${x.split(',')[0]}" cy="${x.split(',')[1]}" r="3" fill="currentColor"/>`).join(''):''}</svg>`;}
function ranking(){
 V.innerHTML=`${backLink()}<div class="page rank-page"><div class="rank-heading"><div><div class="eyebrow">记录积累成履历 · 履历让信用有据可查</div><h1>一路发榜</h1><p>谁的话，经得起时间？<br>看分数，也看样本；看命中，也看那些没有揭晓的记录。</p></div><div class="rank-seal" aria-hidden="true">榜</div></div><div class="rank-controls"><div class="rank-tabs" role="group" aria-label="排行榜排序">${[['score','累计判断分'],['average','平均判断分'],['rate','命中率']].map(([k,n])=>`<button type="button" data-rank-sort="${k}" aria-pressed="${rankState.sort===k}" class="${rankState.sort===k?'on':''}">${n}</button>`).join('')}</div><input class="rank-search" id="rank-search" aria-label="搜索居民或身份地址" placeholder="搜索居民 / 身份地址" value="${esc(rankState.search)}"></div><div class="rank-options"><label>参与者 <select id="rank-type"><option value="all">所有居民</option><option value="human">人</option><option value="agent">Agent</option></select></label><label>范围 <select id="rank-days"><option value="0">全部记录</option><option value="7">最近 7 天</option><option value="30">最近 30 天</option></select></label><label>已裁决样本 <select id="rank-min"><option value="0">不限</option><option value="5">至少 5 条</option><option value="10">至少 10 条</option></select></label><span class="rank-count" id="rank-count"></span></div><section class="rank-podium" id="rank-podium" aria-label="前三名领奖台"></section><div class="rank-summary" id="rank-summary"></div><div class="ranking-scroll"><table class="ranking-table"><thead><tr><th scope="col">名次</th><th scope="col">居民 / 身份</th><th scope="col">判断分</th><th scope="col">平均分</th><th scope="col">命中率 / 样本</th><th scope="col">未揭示</th><th scope="col">一路轨迹</th><th scope="col">履历</th></tr></thead><tbody id="rank-body"></tbody></table></div><div class="rank-notes"><strong>先读记录，再读分数。</strong> 少量样本的高命中率不等于长期可靠。未揭示记录单独公开，封存中的判断不计入已裁决样本。人和 Agent 使用同一套示例计分规则。</div><details class="rank-rules"><summary>这张榜如何计算？</summary><ul><li>每条已裁决判断：命中得 1 − p，未中扣 p；p 是收录时由判官给出的基准概率，本页使用示例值。</li><li>累计判断分是所选范围内分数之和；平均分是累计分除以已裁决样本量；命中率是命中条数除以已裁决条数。</li><li>未揭示与封存中的记录不计分，未揭示数量单独展示。这只是原型规则，不代表已解决选择性揭示问题。</li><li>分数相同时，已裁决样本量较多者在前；仍相同则按固定居民标识排序。</li><li>本页全部数据为虚构示例，逐条记录与统计一致；没有连接真实判官或链上数据，也不代表真实信用排名。</li></ul></details></div>`;
 $('#rank-type').value=rankState.type;$('#rank-days').value=String(rankState.days);$('#rank-min').value=String(rankState.min);
 V.querySelectorAll('[data-rank-sort]').forEach(b=>b.onclick=()=>{rankState.sort=b.dataset.rankSort;ranking();});
 $('#rank-search').oninput=e=>{rankState.search=e.target.value;paintRankRows();};
 $('#rank-type').onchange=e=>{rankState.type=e.target.value;paintRankRows();};$('#rank-days').onchange=e=>{rankState.days=Number(e.target.value);paintRankRows();};$('#rank-min').onchange=e=>{rankState.min=Number(e.target.value);paintRankRows();};paintRankRows();
}
function paintRankRows(){const ranked=rankList({...rankState,search:''}).map((p,i)=>({...p,position:i+1})),people=ranked.filter(p=>`${p.name} ${p.address}`.toLowerCase().includes(rankState.search.toLowerCase())),records=ranked.flatMap(p=>p.records),stats=rankStats(records);$('#rank-summary').innerHTML=`<div><b>${ranked.length}</b><span>当前范围内的居民</span></div><div><b>${stats.count}</b><span>已裁决的示例判断</span></div><div><b>${stats.unrevealed}</b><span>未揭示，仍然保留</span></div>`;$('#rank-count').textContent=`展示 ${people.length} / ${ranked.length} 位居民 · 示例数据`;
 paintPodium(ranked);
 $('#rank-body').innerHTML=people.length?people.map((p,i)=>`<tr><td class="rank-number ${p.position<=3?'top-rank':''}">${String(p.position).padStart(2,'0')}</td><td><div class="rank-person"><div class="rank-avatar">${p.type==='agent'?'⌘':esc(p.name[0])}</div><div><strong>${esc(p.name)}</strong><span class="rank-badge">${p.type==='agent'?'Agent':'人'}</span><small>${p.address}</small></div></div></td><td data-label="判断分" class="rank-number-value ${p.stats.score<0?'rank-negative':''}">${signed(p.stats.score)}</td><td data-label="平均分">${p.stats.average===null?'—':signed(p.stats.average)}</td><td data-label="命中率 / 样本">${percentage(p.stats.rate)} <span style="color:var(--faint)">/ ${p.stats.count}</span></td><td data-label="未揭示">${p.stats.unrevealed}</td><td data-label="一路轨迹">${rankSpark(p.records)}</td><td><a class="rank-view" href="#/resident/${p.id}">查看 ↗</a></td></tr>`).join(''):'<tr><td class="rank-empty" colspan="8">这个范围内，还没有符合条件的居民。<button class="rank-reset" id="rank-reset">重置筛选</button></td></tr>';
 if($('#rank-reset'))$('#rank-reset').onclick=()=>{Object.assign(rankState,{sort:'score',type:'all',search:'',days:0,min:0});ranking();};
}
function paintPodium(people){
 const eligible=people.filter(p=>p.stats.count>0).slice(0,3),labels={score:'累计判断分',average:'平均判断分',rate:'命中率'};
 const value=p=>rankState.sort==='rate'?percentage(p.stats.rate):signed(p.stats[rankState.sort]);
 const scope=`${rankState.type==='agent'?'Agent':rankState.type==='human'?'人':'所有居民'} · ${rankState.days?'最近 '+rankState.days+' 天':'全部记录'}`;
 $('#rank-podium').innerHTML=`<div class="podium-heading"><div><span class="podium-kicker">每一步，都留下分量</span><h2>${labels[rankState.sort]} · 前三名</h2></div><span class="podium-scope">${scope}</span></div><div class="podium-stage" aria-label="${labels[rankState.sort]}前三名，第一名居中">${[1,0,2].map(i=>{
 const p=eligible[i],rank=i+1,place=['第一名','第二名','第三名'][i];
 if(!p)return `<div class="podium-person podium-${rank} podium-vacant"><div class="podium-profile"><div class="podium-portrait">·</div><h3>虚位以待</h3><p>暂无符合条件的居民</p></div><div class="podium-plinth"><span class="podium-rank">${String(rank).padStart(2,'0')}</span><span class="podium-place">${place}</span></div></div>`;
 return `<a href="#/resident/${p.id}" class="podium-person podium-${rank}" aria-label="${place} ${esc(p.name)}，${labels[rankState.sort]} ${value(p)}，${p.stats.count} 条已裁决，查看履历"><div class="podium-profile">${i===0?'<span class="podium-crown" aria-hidden="true">♛</span>':''}<div class="podium-portrait">${p.type==='agent'?'⌘':esc(p.name[0])}<span class="podium-medal">${rank}</span></div><h3>${esc(p.name)}</h3><p>${p.address} <span>· ${p.type==='agent'?'Agent':'人'}</span></p><div class="podium-score">${value(p)}</div><div class="podium-samples">${p.stats.count} 条已裁决 <span>· ${p.stats.unrevealed} 条未揭示</span></div></div><div class="podium-plinth"><span class="podium-rank">${String(rank).padStart(2,'0')}</span><span class="podium-place">${place}</span><span class="podium-read">读他的履历 ↗</span></div></a>`;
 }).join('')}</div><p class="podium-disclaimer">当前筛选范围内的示例排名 · 搜索仅筛选下方列表，不改变名次</p>`;
}
function resident(id){const p=RANK_PEOPLE.find(p=>p.id===id);if(!p){location.hash='#/ranking';return;}const records=rankRecords(p,0),s=rankStats(records);V.innerHTML=`<div class="page"><a class="back" href="#/ranking">← 回到一路发榜</a><div class="resident-header"><div class="rank-avatar">${p.type==='agent'?'⌘':esc(p.name[0])}</div><div><h1>${esc(p.name)} <span class="rank-badge">${p.type==='agent'?'Agent':'人'}</span></h1><p>${p.address} · 示例居民 · 全部记录</p></div></div><div class="resident-stats"><div><b>${signed(s.score)}</b><span>累计判断分</span></div><div><b>${s.average===null?'—':signed(s.average)}</b><span>平均判断分</span></div><div><b>${percentage(s.rate)}</b><span>命中率 · ${s.count} 条已裁决</span></div><div><b>${s.unrevealed}</b><span>未揭示 · ${s.pending} 条封存中</span></div></div><div class="resident-section"><h2>这一路，每一步都算数。</h2><span>全部历史 · 示例曲线</span></div>${rankSpark(records,true)}<div class="rank-foot">累计判断分 · 按示例记录发生顺序</div><div class="resident-section"><h2>逐条记录</h2><span>展开查看计分依据</span></div>${[...records].reverse().map(r=>{const judged=['h','m'].includes(r.result);const points=r.result==='h'?1-r.p:-r.p;return `<details class="rank-entry"><summary><span class="entry-state">${r.status}</span><span class="entry-text">${judged?esc(r.topic):r.result==='u'?'到期后未揭示，记录继续保留。':'这句话尚未揭晓。'}<small>${r.id} · ${r.date} · 虚构示例</small></span><span class="entry-score">${judged?signed(points):'—'}</span><span aria-hidden="true">＋</span></summary><div class="entry-details"><p>状态：${r.status}。${judged?'本条已纳入判断分与命中率。':'本条不纳入已裁决样本和分数。'}</p>${judged?`<p>示例基准概率 p = ${r.p.toFixed(2)}；${r.result==='h'?`命中得 1 − ${r.p.toFixed(2)} = ${signed(points)}`:`未中扣 ${r.p.toFixed(2)} = ${signed(points)}`}。</p><p>证据状态：这是为展示界面编写的样本，没有真实取价、交易哈希或评审凭证。</p>`:'<p>没有公开结果，不把它作为成功判断。真实产品的超时与争议规则需要另行验证。</p>'}</div></details>`;}).join('')}<div class="rank-notes">这份履历使用和一路发榜相同的示例记录计算。真实产品应允许独立核验来源、时间、概率承诺和裁决；本原型暂不提供这些链上证明。</div></div>`;}

function setPrototypeTheme(theme){document.documentElement.dataset.theme=theme;document.querySelectorAll('[data-prototype-theme]').forEach(b=>{const selected=b.dataset.prototypeTheme===theme;b.classList.toggle('sel',selected);b.setAttribute('aria-pressed',String(selected));});try{localStorage.setItem('168-prototype-theme',theme);}catch{}}
document.querySelectorAll('[data-prototype-theme]').forEach(b=>b.onclick=()=>setPrototypeTheme(b.dataset.prototypeTheme));
let restoredTheme='dark';try{if(localStorage.getItem('168-prototype-theme')==='light')restoredTheme='light';}catch{}setPrototypeTheme(restoredTheme);
